package:
  name: cyvlfeat
  version: "0.2"

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.9.1,<1.10
    - cython 0.21.*
    - vlfeat 0.9.*
    - msinttypes r26 [win]

  run:
    - python
    - vlfeat 0.9.*
    - numpy >=1.9.1,<1.10

test:
  imports:
    - cyvlfeat.sift.dsift
    - cyvlfeat.sift.sift

about:
  home: https://github.com/menpo/cyvlfeat/
  license: BSD
