package:
  name: cyvlfeat
  version: {{ CONDACI_VERSION }}

requirements:
  host:
    - cython
    - numpy
    - python
    - scipy
    - setuptools
    - vlfeat

  run:
    - python
    - {{ pin_compatible('vlfeat', min_pin='x.x.x', max_pin='x.x.x') }}
    - {{ pin_compatible('numpy') }}
    - scipy

test:
  requires:
    - pytest
    - pytest-cov
    - scikit-image

  imports:
    - cyvlfeat.fisher.fisher
    - cyvlfeat.generic.generic
    - cyvlfeat.hog.hog
    - cyvlfeat.kmeans.kmeans
    - cyvlfeat.quickshift.quickshift
    - cyvlfeat.sift.dsift
    - cyvlfeat.sift.phow
    - cyvlfeat.sift.sift
    - cyvlfeat.vlad.vlad

  commands:
    - pytest $SP_DIR/cyvlfeat -v --cov=cyvlfeat --cov-config .coveragerc

about:
  home: https://github.com/menpo/cyvlfeat
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'A Python (cython) wrapper of the VLFeat library'
