package:
  name: cyvlfeat
  version: {{ CONDACI_VERSION }}

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.10,<1.11
    - cython 0.23.*
    - vlfeat 0.9.*
    - msinttypes r26 [win]

  run:
    - python
    - vlfeat 0.9.*
    - numpy >=1.10,<1.11

test:
  requires:
    - nose
    - scipy

  imports:
    - cyvlfeat.sift.sift
    - cyvlfeat.sift.dsift
    - cyvlfeat.fisher.fisher
    - cyvlfeat.hog.hog

about:
  home: https://github.com/menpo/cyvlfeat/
  license: BSD
