package:
  name: cyvlfeat
  version: {{ environ['CONDACI_VERSION'] }}

requirements:
  build:
    - python
    - setuptools
    - numpy
    - cython
    - msinttypes [win]

  run:
    - python
    - numpy

test:
  imports:
    - cyvlfeat.sift.dsift
    - cyvlfeat.sift.sift

about:
  home: https://github.com/menpo/cyvlfeat/
  license: BSD
